version: "3.8"

services:
  mariadb:
    image: mariadb:11
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: sie_db
      MARIADB_USER: ${SPRING_DATASOURCE_USERNAME}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  app:
    image: djmaldonado19/sie-backend:${VERSION:-latest}
    container_name: sie_backend
    restart: always
    depends_on:
      - mariadb
    environment:
      DB_URL: ${SPRING_DATASOURCE_URL}
      DB_USER: ${SPRING_DATASOURCE_USERNAME}
      DB_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.mariadb.jdbc.Driver
    ports:
      - "8080:8080"

volumes:
  mariadb_data: