name: CI/CD Pipeline

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [main]

env:
  DOCKER_IMAGE: sie-backend
  DOCKER_USERNAME: dmaldonado
  SERVER_IP: 20.55.81.100
  SERVER_PATH: /opt/springboot-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE }}:${{ github.run_number }} .
          echo "Built Docker image for branch: ${{ github.ref_name }}"

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push to Docker Hub
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag ${{ env.DOCKER_IMAGE }}:${{ github.run_number }} ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:${{ github.run_number }}
          docker tag ${{ env.DOCKER_IMAGE }}:${{ github.run_number }} ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:latest
          docker push ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:${{ github.run_number }}
          docker push ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:latest
          echo "Pushed images to Docker Hub"

      - name: Deploy to server
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Deploying to server ${{ env.SERVER_IP }}"

          # Install sshpass
          sudo apt-get update
          sudo apt-get install -y sshpass

          # Deploy using SSH
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ env.SERVER_IP }} "
            cd ${{ env.SERVER_PATH }} &&
            echo VERSION=${{ github.run_number }} > .env &&
            docker-compose pull &&
            docker-compose down &&
            docker-compose up -d
          "
          echo "Deployment completed"

      - name: Cleanup
        if: always()
        run: |
          docker system prune -f || true
